### PR TITLE
Leverage utils.get_soup_from_url()

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by giacomocerquone** [comment]
Okay before we mess everything up, I locally merged your commit first in the dev branch and after checking out that everything was working, I merged them into the master branch.
But I saw now that you closed them and opened again to switch branch. I'd say to check what has been already merged and remove the pull requests that are not necessary anymore.

Thank you very much and sorry for the inconvenience.

**Comment by cclauss** [comment]
OK

**Comment by cclauss** [comment]
Perhaps the best way forward is to accept the four pull requests into Dev.  Then I can do a diff between Dev and Master to know what mods still needs to be proposed.

**Comment by cclauss** [comment]
OK... I have reviewed this one vs. dev, Please accept this Pull Request.

**Comment by cclauss** [comment]
OK...  I have diffed all four pull requests and all four should be accepted.  When this accepted all four then test `dev` to make sure that it does what you want it to do.  You should open `issues` if you don't like how something is working so we can have focused discussions on topics.

**Pull request closed without merging**
